using Microsoft.Extensions.AI;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Rag.NET.Abstractions;
using Rag.NET.HyDE;
using Rag.NET.Models.Options;
using Rag.NET.MultiQuery;
using Rag.NET.QueryTechniques.ContextualCompression;

namespace Rag.NET.QueryTechniques;

public static class RagBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="LlmQueryExpander"/> as the <see cref="IQueryExpander"/>.
    /// When registered, the pipeline expands each query into
    /// <see cref="MultiQueryOptions.VariantCount"/> alternatives, fans out to the vector store
    /// in parallel, and merges deduplicated results.
    /// </summary>
    /// <remarks>
    /// Requires <c>IChatClient</c> to be registered in DI.
    /// Per-call opt-out: pass <c>new RetrievalOptions { UseMultiQuery = false }</c>.
    /// </remarks>
    /// <param name="builder">The RAG builder.</param>
    /// <param name="configure">Optional delegate to configure <see cref="MultiQueryOptions"/>.</param>
    public static TBuilder UseMultiQueryRetrieval<TBuilder>(this TBuilder builder, Action<MultiQueryOptions>? configure = null)
        where TBuilder : IRagBuilder
    {
        var options = new MultiQueryOptions();
        configure?.Invoke(options);
        if (options.VariantCount < 1)
        {
            throw new ArgumentOutOfRangeException(nameof(configure),
                $"{nameof(MultiQueryOptions)}.{nameof(MultiQueryOptions.VariantCount)} ({options.VariantCount}) must be at least 1.");
        }
        builder.Services.AddSingleton(options);
        builder.Services.AddSingleton<IQueryExpander, LlmQueryExpander>();
        return builder;
    }

    /// <summary>
    /// Registers <see cref="LlmHypotheticalDocumentGenerator"/> as the <see cref="IHypotheticalDocumentGenerator"/>.
    /// When registered, the retriever embeds a hypothetical document generated by the LLM
    /// instead of the raw query, improving recall for asymmetric retrieval (short query vs. long document).
    /// </summary>
    /// <remarks>
    /// Requires <c>IChatClient</c> to be registered in DI.
    /// Per-call opt-out: pass <c>new RetrievalOptions { UseHyde = false }</c>.
    /// </remarks>
    /// <param name="builder">The RAG builder.</param>
    /// <param name="configure">Optional delegate to configure <see cref="HydeOptions"/>.</param>
    public static TBuilder UseHyde<TBuilder>(this TBuilder builder, Action<HydeOptions>? configure = null)
        where TBuilder : IRagBuilder
    {
        var options = new HydeOptions();
        configure?.Invoke(options);
        if (options.HypothesisCount < 1)
        {
            throw new ArgumentOutOfRangeException(nameof(configure),
                $"{nameof(HydeOptions)}.{nameof(HydeOptions.HypothesisCount)} ({options.HypothesisCount}) must be at least 1.");
        }
        builder.Services.AddSingleton(options);
        builder.Services.AddSingleton<IHypotheticalDocumentGenerator, LlmHypotheticalDocumentGenerator>();
        return builder;
    }

    /// <summary>
    /// Registers an <see cref="IContextualCompressor"/> that the answer engines
    /// (<c>ChatAnswerEngine</c>, <c>MapReduceAnswerEngine</c>, <c>RefineAnswerEngine</c>)
    /// invoke before building the LLM prompt. Choose between extractive (embedding-similarity,
    /// no LLM) or abstractive (per-chunk parallel LLM call) compression via
    /// <see cref="ContextualCompressionOptions.Strategy"/>.
    /// </summary>
    /// <remarks>
    /// Extractive mode requires an <c>IEmbeddingGenerator&lt;string, Embedding&lt;float&gt;&gt;</c> registered in DI.
    /// Abstractive mode requires an <c>IChatClient</c>.
    /// Per-call opt-out: set <c>RagOptions.SkipCompression = true</c>.
    /// </remarks>
    /// <param name="builder">The RAG builder.</param>
    /// <param name="configure">Optional delegate to configure <see cref="ContextualCompressionOptions"/>.</param>
    public static TBuilder UseContextualCompression<TBuilder>(
        this TBuilder builder,
        Action<ContextualCompressionOptions>? configure = null)
        where TBuilder : IRagBuilder
    {
        var options = new ContextualCompressionOptions();
        configure?.Invoke(options);
        ValidateContextualCompressionOptions(options);

        builder.Services.AddSingleton(options);

        if (options.Strategy == ContextualCompressionStrategy.Extractive)
        {
            builder.Services.AddSingleton<IContextualCompressor>(sp =>
                new ExtractiveCompressor(
                    sp.GetRequiredService<IEmbeddingGenerator<string, Embedding<float>>>(),
                    sp.GetRequiredService<ContextualCompressionOptions>(),
                    sp.GetService<ILogger<ExtractiveCompressor>>()));
        }
        else
        {
            builder.Services.AddSingleton<IContextualCompressor>(sp =>
                new LlmAbstractiveCompressor(
                    sp.GetRequiredService<IChatClient>(),
                    sp.GetRequiredService<ContextualCompressionOptions>(),
                    sp.GetService<ILogger<LlmAbstractiveCompressor>>()));
        }

        return builder;
    }

    private static void ValidateContextualCompressionOptions(ContextualCompressionOptions opts)
    {
        if (opts.KeepTopSentences is null && opts.MaxTokensPerChunk is null)
        {
            throw new InvalidOperationException(
                $"{nameof(ContextualCompressionOptions)}: at least one of " +
                $"{nameof(ContextualCompressionOptions.KeepTopSentences)} or " +
                $"{nameof(ContextualCompressionOptions.MaxTokensPerChunk)} must be set.");
        }
        if (opts.KeepTopSentences is { } n && n <= 0)
        {
            throw new InvalidOperationException(
                $"{nameof(ContextualCompressionOptions)}.{nameof(ContextualCompressionOptions.KeepTopSentences)} must be positive.");
        }
        if (opts.MaxTokensPerChunk is { } m && m <= 0)
        {
            throw new InvalidOperationException(
                $"{nameof(ContextualCompressionOptions)}.{nameof(ContextualCompressionOptions.MaxTokensPerChunk)} must be positive.");
        }
    }
}
